# Copyright (c) 2026 Mike Grier

[package]
name        = "globazog"
description = "A high-performance, Windows-first globbing and directory-traversal library for Rust."
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
license.workspace       = true
repository.workspace    = true
homepage.workspace      = true
documentation.workspace = true
keywords    = ["glob", "globbing", "filesystem", "directory", "traversal"]
categories  = ["filesystem"]

[dependencies]

[dev-dependencies]
