# Copyright (c) 2026 Mike Grier
#
# Regenerates crates/globazog/src/syntax/upcase.rs from the Windows OS uppercase
# table (RtlUpcaseUnicodeChar) — the same table CompareStringOrdinal(bIgnoreCase)
# and NTFS-style ordinal case-insensitive comparison use. Run on Windows.
# See DESIGN-NOTES.md D-28. The emitted table is a frozen snapshot (gospel).

$ErrorActionPreference = 'Stop'

Add-Type -TypeDefinition @'
using System;
using System.Runtime.InteropServices;
public static class NtUpcase {
    [DllImport("ntdll.dll", CharSet = CharSet.Unicode)]
    public static extern char RtlUpcaseUnicodeChar(char c);
}
'@

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('// Copyright (c) 2026 Mike Grier')
$lines.Add('')
$lines.Add('//! Generated by tools/gen-upcase-table.ps1 from the Windows OS uppercase table')
$lines.Add('//! (RtlUpcaseUnicodeChar) - the table CompareStringOrdinal(bIgnoreCase) uses (D-28).')
$lines.Add('//! Do not edit by hand; regenerate with the script. Frozen snapshot (gospel).')
$lines.Add('')
    $lines.Add('/// Sorted BMP code-unit -> uppercase code-unit mapping; identity mappings are omitted.')
$lines.Add('pub(crate) static UPCASE: &[(u16, u16)] = &[')

$count = 0
for ($i = 0; $i -le 0xFFFF; $i++) {
    $u = [int][NtUpcase]::RtlUpcaseUnicodeChar([char]$i)
    if ($u -ne $i) {
        $lines.Add(('    (0x{0:X4}, 0x{1:X4}),' -f $i, $u))
        $count++
    }
}
$lines.Add('];')

$path = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\crates\globazog\src\syntax\upcase.rs'))
$text = [string]::Join("`n", $lines) + "`n"
$enc = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($path, $text, $enc)
Write-Output ("Wrote $count mapping entries to $path")
